# Example CRS Client Configuration File
#
# This file shows all available configuration options for the CRS client.
# Copy this file and modify it for your needs, then use it with:
#   crs-client --config path/to/config.toml
#
# Command line options will override settings in this file.

# URL of the CRS server (required)
server = "http://172.20.1.52:8081"
